services:
  server:
    build:
      context: server
    ports:
      - "8000:8000"
  client:
    build:
      context: client
      args:
        VITE_STYLEGAN_API: "http://localhost:8000"
    ports:
      - "8080:80"
